
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

car_diff_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: ['left_front_wheel_joint', left_back_wheel_joint']
  right_wheel: ['right_front_wheel_joint', right_back_wheel_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  base_frame_id: base_link

  enable_odom_tf: false

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # rad/s^2