car:
  #Publish all transforms
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100 
  
  #Velocity Controllers
  left_front_wheel_controller:
    type: velocity_contollers/JointVelocityController
    joint: left_front_wheel_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}

  left_back_wheel_controller:
    type: velocity_contollers/JointVelocityController
    joint: left_back_wheel_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}
  right_front_wheel_controller:
    type: velocity_contollers/JointVelocityController
    joint: right_front_wheel_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}
  right_back_wheel_controller:
    type: velocity_contollers/JointVelocityController
    joint: right_back_wheel_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}

  base_frame_id : base_link

/car/gazebo_ros_control:
  pid_gains:
    left_front_wheel_joint:
      p: 1.001
      i: 0.00
      d: 0.00
    left_back_wheel_joint:
      p: 1.001
      i: 0.00
      d: 0.00
    right_front_wheel_joint:
      p: 1.001
      i: 0.00
      d: 0.00
    right_back_wheel_joint:
      p: 1.001
      i: 0.00
      d: 0.00